"""Tests for scripts/reproducible_build.py's pure logic.

The script's real job -- create a venv, install into it, run the test suite
and the pipeline through it, write a manifest -- is I/O and subprocess work
with nothing meaningful to fake without testing a mock instead of the
script. That end-to-end behavior is verified by actually running it (see
docs/reproducible_builds.md); what's covered here is the one piece of real
logic that can silently drift and produce a wrong answer without ever
raising: parsing the lockfile's pins and comparing them to what got
installed.
"""

from __future__ import annotations

from pathlib import Path

import pytest

import scripts.reproducible_build as reproducible_build


def write_lockfile(tmp_path: Path, text: str) -> Path:
    path = tmp_path / "requirements-dev.txt"
    path.write_text(text, encoding="utf-8")
    return path


class TestParseLockfilePins:
    def test_parses_name_and_version(self, tmp_path):
        lockfile = write_lockfile(tmp_path, "pandas==3.0.5\nrequests==2.34.2\n")
        assert reproducible_build.parse_lockfile_pins(lockfile) == {
            "pandas": "3.0.5", "requests": "2.34.2",
        }

    def test_strips_the_pip_compile_via_trailer(self, tmp_path):
        lockfile = write_lockfile(tmp_path, "certifi==2026.7.22\n    # via requests\n")
        assert reproducible_build.parse_lockfile_pins(lockfile) == {"certifi": "2026.7.22"}

    def test_skips_comments_and_the_autogenerated_header(self, tmp_path):
        lockfile = write_lockfile(
            tmp_path,
            "#\n# This file is autogenerated by pip-compile\n#\npandas==3.0.5\n",
        )
        assert reproducible_build.parse_lockfile_pins(lockfile) == {"pandas": "3.0.5"}

    def test_skips_a_requirements_include_line(self, tmp_path):
        lockfile = write_lockfile(tmp_path, "-r requirements.in\npytest==9.1.1\n")
        assert reproducible_build.parse_lockfile_pins(lockfile) == {"pytest": "9.1.1"}

    def test_skips_a_line_with_no_pin_at_all(self, tmp_path):
        """A malformed or unpinned line must never be silently treated as
        "no constraint" -- it's dropped from the comparison entirely rather
        than accidentally matching anything installed."""
        lockfile = write_lockfile(tmp_path, "pandas>=3.0\nrequests==2.34.2\n")
        assert reproducible_build.parse_lockfile_pins(lockfile) == {"requests": "2.34.2"}

    def test_normalizes_name_case_and_underscores(self, tmp_path):
        """pip freeze and a hand-written lockfile can disagree on case and
        on underscore-vs-hyphen for the same real package (PyYAML vs
        pyyaml, typing_extensions vs typing-extensions) -- both sides of
        the comparison must normalize the same way or every such package
        would falsely report as mismatched."""
        lockfile = write_lockfile(tmp_path, "PyYAML==6.0.3\ntyping_extensions==4.16.0\n")
        assert reproducible_build.parse_lockfile_pins(lockfile) == {
            "pyyaml": "6.0.3", "typing-extensions": "4.16.0",
        }

    def test_empty_file_yields_no_pins(self, tmp_path):
        lockfile = write_lockfile(tmp_path, "")
        assert reproducible_build.parse_lockfile_pins(lockfile) == {}


class TestVenvPython:
    def test_windows_path_shape(self, monkeypatch, tmp_path):
        monkeypatch.setattr(reproducible_build.os, "name", "nt")
        assert reproducible_build.venv_python(tmp_path) == tmp_path / "Scripts" / "python.exe"

    def test_posix_path_shape(self, monkeypatch, tmp_path):
        monkeypatch.setattr(reproducible_build.os, "name", "posix")
        assert reproducible_build.venv_python(tmp_path) == tmp_path / "bin" / "python"


class TestSupportedPython:
    def test_supported_versions(self):
        assert reproducible_build.python_is_supported((3, 12, 10))
        assert reproducible_build.python_is_supported((3, 13, 7))

    def test_unsupported_versions(self):
        assert not reproducible_build.python_is_supported((3, 11, 9))
        assert not reproducible_build.python_is_supported((3, 14, 3))


class TestProjectChildPath:
    def test_relative_path_resolves_under_repository(self, monkeypatch, tmp_path):
        root = tmp_path / "repo"
        root.mkdir()
        monkeypatch.setattr(reproducible_build, "ROOT", root)

        assert reproducible_build.project_child_path("scratch", "--venv-dir") == root / "scratch"

    def test_repository_root_is_rejected(self, monkeypatch, tmp_path):
        monkeypatch.setattr(reproducible_build, "ROOT", tmp_path)

        with pytest.raises(ValueError, match="repository root"):
            reproducible_build.project_child_path(".", "--venv-dir")

    def test_path_outside_repository_is_rejected(self, monkeypatch, tmp_path):
        root = tmp_path / "repo"
        root.mkdir()
        monkeypatch.setattr(reproducible_build, "ROOT", root)

        with pytest.raises(ValueError, match="inside the repository"):
            reproducible_build.project_child_path(str(tmp_path / "elsewhere"), "--out-dir")


class TestPathsOverlap:
    def test_equal_or_nested_paths_overlap(self, tmp_path):
        assert reproducible_build.paths_overlap(tmp_path / "a", tmp_path / "a")
        assert reproducible_build.paths_overlap(tmp_path / "a", tmp_path / "a" / "b")

    def test_sibling_paths_do_not_overlap(self, tmp_path):
        assert not reproducible_build.paths_overlap(tmp_path / "a", tmp_path / "b")


class TestReplaceableBuildVenv:
    def test_plain_directory_is_not_replaceable(self, tmp_path):
        assert not reproducible_build.is_replaceable_build_venv(tmp_path)

    def test_marker_identifies_a_build_venv(self, tmp_path):
        (tmp_path / reproducible_build.BUILD_VENV_MARKER).write_text("marker")
        assert reproducible_build.is_replaceable_build_venv(tmp_path)

    def test_legacy_default_venv_shape_is_replaceable(self, monkeypatch, tmp_path):
        (tmp_path / "pyvenv.cfg").write_text("home = test")
        interpreter = tmp_path / "bin" / "python"
        interpreter.parent.mkdir()
        interpreter.touch()
        monkeypatch.setattr(reproducible_build.os, "name", "posix")
        monkeypatch.setattr(reproducible_build, "DEFAULT_VENV_DIR", tmp_path)

        assert reproducible_build.is_replaceable_build_venv(tmp_path)

    def test_unmarked_non_default_venv_is_not_replaceable(self, monkeypatch, tmp_path):
        ordinary_venv = tmp_path / "venv"
        ordinary_venv.mkdir()
        (ordinary_venv / "pyvenv.cfg").write_text("home = test")
        interpreter = ordinary_venv / "bin" / "python"
        interpreter.parent.mkdir()
        interpreter.touch()
        monkeypatch.setattr(reproducible_build.os, "name", "posix")
        monkeypatch.setattr(
            reproducible_build, "DEFAULT_VENV_DIR", tmp_path / ".build-venv"
        )

        assert not reproducible_build.is_replaceable_build_venv(ordinary_venv)


class TestRealLockfileHasNoDriftAgainstItself:
    def test_the_committed_requirements_dev_txt_parses_to_at_least_pandas_and_pytest(self):
        """A cheap real-file smoke check: this project's actual lockfile is
        parseable and contains what it's supposed to. Catches a
        hand-edited requirements-dev.txt (it should only ever be
        regenerated by pip-compile) going out of the format this script
        expects."""
        pins = reproducible_build.parse_lockfile_pins(reproducible_build.LOCKFILE)
        assert "pandas" in pins
        assert "pytest" in pins
        assert "playwright" in pins
