"""Tests for scripts/reproducible_build.py's pure logic.

The script's real job -- create a venv, install into it, run the test suite
and the pipeline through it, write a manifest -- is I/O and subprocess work
with nothing meaningful to fake without testing a mock instead of the
script. That end-to-end behavior is verified by actually running it (see
docs/reproducible_builds.md); what's covered here is the one piece of real
logic that can silently drift and produce a wrong answer without ever
raising: parsing the lockfile's pins and comparing them to what got
installed.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import pytest

import scripts.reproducible_build as reproducible_build


def write_lockfile(tmp_path: Path, text: str) -> Path:
    path = tmp_path / "requirements-dev.txt"
    path.write_text(text, encoding="utf-8")
    return path


class TestParseLockfilePins:
    def test_parses_name_and_version(self, tmp_path):
        lockfile = write_lockfile(tmp_path, "pandas==3.0.5\nrequests==2.34.2\n")
        assert reproducible_build.parse_lockfile_pins(lockfile) == {
            "pandas": "3.0.5", "requests": "2.34.2",
        }

    def test_strips_the_pip_compile_via_trailer(self, tmp_path):
        lockfile = write_lockfile(tmp_path, "certifi==2026.7.22\n    # via requests\n")
        assert reproducible_build.parse_lockfile_pins(lockfile) == {"certifi": "2026.7.22"}

    def test_skips_comments_and_the_autogenerated_header(self, tmp_path):
        lockfile = write_lockfile(
            tmp_path,
            "#\n# This file is autogenerated by pip-compile\n#\npandas==3.0.5\n",
        )
        assert reproducible_build.parse_lockfile_pins(lockfile) == {"pandas": "3.0.5"}

    def test_rejects_a_requirements_include_the_manifest_cannot_audit(self, tmp_path):
        lockfile = write_lockfile(tmp_path, "-r requirements.in\npytest==9.1.1\n")
        with pytest.raises(ValueError, match=r"line 1.*exact name==version pin"):
            reproducible_build.parse_lockfile_pins(lockfile)

    @pytest.mark.parametrize(
        "requirement",
        [
            "pandas>=3.0",
            "pandas~=3.0",
            "pandas",
            "pandas @ https://example.invalid/archive.whl",
            "pandas==3.*",
            "--index-url https://example.invalid/simple",
            "pandas==3.0.5 \\",
        ],
    )
    def test_rejects_a_line_with_no_exact_pin(self, tmp_path, requirement):
        """An unpinned requirement must not escape manifest verification."""
        lockfile = write_lockfile(tmp_path, f"{requirement}\nrequests==2.34.2\n")
        with pytest.raises(ValueError, match=r"line 1.*exact name==version pin"):
            reproducible_build.parse_lockfile_pins(lockfile)

    def test_normalizes_name_case_and_underscores(self, tmp_path):
        """pip freeze and a hand-written lockfile can disagree on case and
        on underscore-vs-hyphen for the same real package (PyYAML vs
        pyyaml, typing_extensions vs typing-extensions) -- both sides of
        the comparison must normalize the same way or every such package
        would falsely report as mismatched."""
        lockfile = write_lockfile(
            tmp_path,
            "PyYAML==6.0.3\ntyping_extensions==4.16.0\ndemo.pkg==1.0\n",
        )
        assert reproducible_build.parse_lockfile_pins(lockfile) == {
            "pyyaml": "6.0.3", "typing-extensions": "4.16.0", "demo-pkg": "1.0",
        }

    def test_rejects_an_empty_lockfile(self, tmp_path):
        lockfile = write_lockfile(tmp_path, "")
        with pytest.raises(ValueError, match="contains no exact pins"):
            reproducible_build.parse_lockfile_pins(lockfile)

    def test_rejects_duplicate_normalized_package_names(self, tmp_path):
        lockfile = write_lockfile(
            tmp_path,
            "typing_extensions==4.16.0\ntyping-extensions==4.16.0\n",
        )
        with pytest.raises(ValueError, match=r"line 2.*duplicates.*typing-extensions"):
            reproducible_build.parse_lockfile_pins(lockfile)


def test_invalid_lockfile_fails_before_an_existing_build_venv_is_removed(
    monkeypatch, tmp_path
):
    root = tmp_path / "repo"
    root.mkdir()
    lockfile = write_lockfile(root, "pandas>=3.0\n")
    fixtures = root / "fixtures"
    fixtures.mkdir()
    (fixtures / "sample.json").write_text("{}", encoding="utf-8")
    venv_dir = root / ".build-venv"
    venv_dir.mkdir()
    marker = venv_dir / reproducible_build.BUILD_VENV_MARKER
    marker.write_text("keep", encoding="utf-8")

    monkeypatch.setattr(reproducible_build, "ROOT", root)
    monkeypatch.setattr(reproducible_build, "LOCKFILE", lockfile)
    monkeypatch.setattr(reproducible_build, "CI_BUILD_DIR", root / "ci-build")
    monkeypatch.setattr(reproducible_build, "python_is_supported", lambda: True)
    monkeypatch.setattr(
        reproducible_build.subprocess,
        "run",
        lambda *args, **kwargs: pytest.fail("invalid lockfile started a subprocess"),
    )

    with pytest.raises(SystemExit) as exc_info:
        reproducible_build.main(
            [
                "--venv-dir", str(venv_dir),
                "--out-dir", str(root / "dist"),
                "--fixtures", str(fixtures),
            ]
        )

    assert exc_info.value.code == 1
    assert marker.read_text(encoding="utf-8") == "keep"


class TestVenvPython:
    def test_windows_path_shape(self, monkeypatch, tmp_path):
        monkeypatch.setattr(reproducible_build.os, "name", "nt")
        assert reproducible_build.venv_python(tmp_path) == tmp_path / "Scripts" / "python.exe"

    def test_posix_path_shape(self, monkeypatch, tmp_path):
        monkeypatch.setattr(reproducible_build.os, "name", "posix")
        assert reproducible_build.venv_python(tmp_path) == tmp_path / "bin" / "python"


class TestReproducibleSubprocessEnvironment:
    def test_removes_python_and_pytest_overrides_but_preserves_install_access(self):
        source = {
            "PATH": "system-path",
            "PYTHONHOME": "contaminated-home",
            "pythonpath": "contaminated-imports",
            "PYTEST_ADDOPTS": "--collect-only",
            "PyTeSt_Plugins": "ambient_plugin",
            "PYTHONNOUSERSITE": "0",
            "PIP_INDEX_URL": "https://packages.example/simple",
            "HTTPS_PROXY": "https://proxy.example",
            "PIP_CERT": "C:/certificates/corporate.pem",
        }

        cleaned = reproducible_build.reproducible_subprocess_environment(source)

        assert not {
            key for key in cleaned
            if key.upper() in {"PYTHONHOME", "PYTHONPATH"}
            or key.upper().startswith("PYTEST_")
        }
        assert cleaned["PYTHONNOUSERSITE"] == "1"
        assert cleaned["PATH"] == source["PATH"]
        assert cleaned["PIP_INDEX_URL"] == source["PIP_INDEX_URL"]
        assert cleaned["HTTPS_PROXY"] == source["HTTPS_PROXY"]
        assert cleaned["PIP_CERT"] == source["PIP_CERT"]

    def test_ambient_collect_only_cannot_skip_the_build_test_run(
        self, monkeypatch, tmp_path
    ):
        marker = tmp_path / "test-ran"
        test_file = tmp_path / "test_marker.py"
        test_file.write_text(
            "from pathlib import Path\n"
            f"def test_executes(): Path({str(marker)!r}).write_text('yes')\n",
            encoding="utf-8",
        )
        monkeypatch.setenv("PYTEST_ADDOPTS", "--collect-only")
        monkeypatch.setattr(
            reproducible_build, "venv_python", lambda _venv_dir: Path(sys.executable)
        )

        reproducible_build.run_in_venv(
            tmp_path,
            ["-m", "pytest", str(test_file), "-q"],
            "Run marker regression",
            cwd=tmp_path,
        )

        assert marker.read_text(encoding="utf-8") == "yes"

    def test_ambient_pythonpath_cannot_load_sitecustomize(
        self, monkeypatch, tmp_path
    ):
        marker = tmp_path / "sitecustomize-loaded"
        ambient = tmp_path / "ambient"
        ambient.mkdir()
        (ambient / "sitecustomize.py").write_text(
            "from pathlib import Path\n"
            f"Path({str(marker)!r}).write_text('loaded')\n",
            encoding="utf-8",
        )
        monkeypatch.setenv("PYTHONPATH", str(ambient))
        monkeypatch.setattr(
            reproducible_build, "venv_python", lambda _venv_dir: Path(sys.executable)
        )

        reproducible_build.run_in_venv(
            tmp_path, ["-c", "pass"], "Ignore ambient PYTHONPATH", cwd=tmp_path
        )

        assert not marker.exists()


class TestSupportedPython:
    def test_supported_versions(self):
        assert reproducible_build.python_is_supported((3, 12, 10))
        assert reproducible_build.python_is_supported((3, 13, 7))

    def test_unsupported_versions(self):
        assert not reproducible_build.python_is_supported((3, 11, 9))
        assert not reproducible_build.python_is_supported((3, 14, 3))


class TestReadVersion:
    def test_reads_the_stripped_contents_of_the_version_file(self, monkeypatch, tmp_path):
        version_file = tmp_path / "VERSION"
        version_file.write_text("1.0.0-rc1\n", encoding="utf-8")
        monkeypatch.setattr(reproducible_build, "VERSION_FILE", version_file)

        assert reproducible_build.read_version() == "1.0.0-rc1"

    def test_missing_version_file_is_none_not_an_error(self, monkeypatch, tmp_path):
        """A repo without a VERSION file yet (or one checked out before this
        existed) must still be able to build -- version is real release
        metadata this manifest reports when available, not a build
        requirement."""
        monkeypatch.setattr(reproducible_build, "VERSION_FILE", tmp_path / "VERSION")

        assert reproducible_build.read_version() is None

    def test_a_blank_version_file_is_none_not_an_empty_string(self, monkeypatch, tmp_path):
        version_file = tmp_path / "VERSION"
        version_file.write_text("   \n", encoding="utf-8")
        monkeypatch.setattr(reproducible_build, "VERSION_FILE", version_file)

        assert reproducible_build.read_version() is None

    def test_the_committed_version_file_is_a_real_semver_string(self):
        """The actual repo-root VERSION file this project ships, not a
        fixture -- catches it going missing or unparseable."""
        version = reproducible_build.read_version()
        assert version is not None
        assert re.match(r"^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$", version), version


class TestProjectChildPath:
    def test_relative_path_resolves_under_repository(self, monkeypatch, tmp_path):
        root = tmp_path / "repo"
        root.mkdir()
        monkeypatch.setattr(reproducible_build, "ROOT", root)

        assert reproducible_build.project_child_path("scratch", "--venv-dir") == root / "scratch"

    def test_repository_root_is_rejected(self, monkeypatch, tmp_path):
        monkeypatch.setattr(reproducible_build, "ROOT", tmp_path)

        with pytest.raises(ValueError, match="repository root"):
            reproducible_build.project_child_path(".", "--venv-dir")

    def test_path_outside_repository_is_rejected(self, monkeypatch, tmp_path):
        root = tmp_path / "repo"
        root.mkdir()
        monkeypatch.setattr(reproducible_build, "ROOT", root)

        with pytest.raises(ValueError, match="inside the repository"):
            reproducible_build.project_child_path(str(tmp_path / "elsewhere"), "--out-dir")


class TestPathsOverlap:
    def test_equal_or_nested_paths_overlap(self, tmp_path):
        assert reproducible_build.paths_overlap(tmp_path / "a", tmp_path / "a")
        assert reproducible_build.paths_overlap(tmp_path / "a", tmp_path / "a" / "b")

    def test_sibling_paths_do_not_overlap(self, tmp_path):
        assert not reproducible_build.paths_overlap(tmp_path / "a", tmp_path / "b")


class TestReplaceableBuildVenv:
    def test_plain_directory_is_not_replaceable(self, tmp_path):
        assert not reproducible_build.is_replaceable_build_venv(tmp_path)

    def test_marker_identifies_a_build_venv(self, tmp_path):
        (tmp_path / reproducible_build.BUILD_VENV_MARKER).write_text("marker")
        assert reproducible_build.is_replaceable_build_venv(tmp_path)

    def test_legacy_default_venv_shape_is_replaceable(self, monkeypatch, tmp_path):
        (tmp_path / "pyvenv.cfg").write_text("home = test")
        interpreter = tmp_path / "bin" / "python"
        interpreter.parent.mkdir()
        interpreter.touch()
        monkeypatch.setattr(reproducible_build.os, "name", "posix")
        monkeypatch.setattr(reproducible_build, "DEFAULT_VENV_DIR", tmp_path)

        assert reproducible_build.is_replaceable_build_venv(tmp_path)

    def test_unmarked_non_default_venv_is_not_replaceable(self, monkeypatch, tmp_path):
        ordinary_venv = tmp_path / "venv"
        ordinary_venv.mkdir()
        (ordinary_venv / "pyvenv.cfg").write_text("home = test")
        interpreter = ordinary_venv / "bin" / "python"
        interpreter.parent.mkdir()
        interpreter.touch()
        monkeypatch.setattr(reproducible_build.os, "name", "posix")
        monkeypatch.setattr(
            reproducible_build, "DEFAULT_VENV_DIR", tmp_path / ".build-venv"
        )

        assert not reproducible_build.is_replaceable_build_venv(ordinary_venv)


class TestRealLockfileHasNoDriftAgainstItself:
    def test_the_committed_requirements_dev_txt_parses_to_at_least_pandas_and_pytest(self):
        """A cheap real-file smoke check: this project's actual lockfile is
        parseable and contains what it's supposed to. Catches a
        hand-edited requirements-dev.txt (it should only ever be
        regenerated by pip-compile) going out of the format this script
        expects."""
        pins = reproducible_build.parse_lockfile_pins(reproducible_build.LOCKFILE)
        assert "pandas" in pins
        assert "pytest" in pins
        assert "playwright" in pins
